// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLy_KyTucXa.Data;

#nullable disable

namespace QuanLy_KyTucXa.Migrations
{
    [DbContext(typeof(QLKTXDbContext))]
    [Migration("20260304101720_ThemBangLichSuDongTien")]
    partial class ThemBangLichSuDongTien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLy_KyTucXa.Data.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaQuanLy")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MSSV");

                    b.HasIndex("MaQuanLy");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.LichSuDongTien", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamDongTien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDong")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ThangDongTien")
                        .HasColumnType("int");

                    b.HasKey("MaThanhToan");

                    b.ToTable("LichSuDongTiens");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("MaToaNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongDangO")
                        .HasColumnType("int");

                    b.Property<decimal>("TienDienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaToaNha");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.QuanLy", b =>
                {
                    b.Property<string>("MaQuanLy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTenQuanLy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaToaQuanLy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaQuanLy");

                    b.HasIndex("MaToaQuanLy");

                    b.ToTable("QuanLys");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.SinhVien", b =>
                {
                    b.Property<string>("MSSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVao")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MSSV");

                    b.HasIndex("MaPhong");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.TaiKhoan", b =>
                {
                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TenTaiKhoan");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.ToaNha", b =>
                {
                    b.Property<string>("MaToaNha")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongPhong")
                        .HasColumnType("int");

                    b.Property<string>("TenToaNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaToaNha");

                    b.ToTable("ToaNhas");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanLy_KyTucXa.Data.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.HoaDon", b =>
                {
                    b.HasOne("QuanLy_KyTucXa.Data.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MSSV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLy_KyTucXa.Data.QuanLy", "QuanLy")
                        .WithMany()
                        .HasForeignKey("MaQuanLy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuanLy");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.Phong", b =>
                {
                    b.HasOne("QuanLy_KyTucXa.Data.ToaNha", "ToaNha")
                        .WithMany("Phongs")
                        .HasForeignKey("MaToaNha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToaNha");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.QuanLy", b =>
                {
                    b.HasOne("QuanLy_KyTucXa.Data.ToaNha", "ToaNha")
                        .WithMany()
                        .HasForeignKey("MaToaQuanLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToaNha");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.SinhVien", b =>
                {
                    b.HasOne("QuanLy_KyTucXa.Data.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("QuanLy_KyTucXa.Data.ToaNha", b =>
                {
                    b.Navigation("Phongs");
                });
#pragma warning restore 612, 618
        }
    }
}
